In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
from datetime import datetime
import time
import warnings
warnings.filterwarnings("ignore")

from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
from sklearn.metrics import accuracy_score,f1_score,recall_score,precision_score,confusion_matrix,ConfusionMatrixDisplay,roc_curve,roc_auc_score,precision_recall_curve
from sklearn.ensemble import RandomForestClassifier , StackingClassifier
from sklearn.svm import SVC
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
# from lightgbm import LGBMClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression,Lasso
from sklearn.preprocessing import Binarizer
from sklearn.model_selection import cross_val_score,GridSearchCV

# 한글 깨짐 방지
import matplotlib.pyplot as plt
plt.rcParams['font.family'] = 'malgun Gothic'

In [2]:
train=pd.read_csv('../data/train_상장_1대1.csv', encoding='euc-kr')
test=pd.read_csv('../data/test_상장_1대1.csv',encoding='euc-kr')

In [3]:
X_train_int=train[['부채비율', '총자본회전률', '매출액대비잉여현금흐름', 'PBR', '총자산대비영업현금흐름',
       '자기자본증가율', '총자본투자효율', '총자본순이익률', '매출액영업이익률']]

X_test_int=test[['부채비율', '총자본회전률', '매출액대비잉여현금흐름', 'PBR', '총자산대비영업현금흐름',
       '자기자본증가율', '총자본투자효율', '총자본순이익률', '매출액영업이익률']]

In [4]:
X_train = train.drop('t-1감사의견코드',axis=1)
y_train = train[['t-1감사의견코드']]

X_test = test.drop('t-1감사의견코드',axis=1)
y_test = test[['t-1감사의견코드']]

In [5]:
X_train_sc = X_train
X_test_sc = X_test

In [6]:
X_train_sum = X_train_sc
X_test_sum = X_test_sc

In [7]:
import pandas as pd
import numpy as np
from pytorch_tabnet.tab_model import TabNetClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

def evaluate_tabnet(X_train, y_train, X_test, y_test):
    # Stratified 5-fold 교차검증 설정
    cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=0)

    # 최적 하이퍼파라미터 설정 (여기서는 고정값으로 사용)
    best_params = {
        'n_d': 8,  # Number of decision steps (also known as the number of features for attention)
        'n_a': 8,  # Number of attention features (output dimension of each attention head)
        'n_steps': 3,  # Number of steps in the architecture (usually between 3 and 10)
        'gamma': 1.5,  # The factor by which to scale the contribution of each augmented sample
        'n_independent': 2,  # Number of independent GLU layers in each decision step
        'n_shared': 2,  # Number of shared GLU layers in each decision step
        'lambda_sparse': 0.001  # The sparsity loss weight
    }

    # 각 fold 별 평가 지표를 저장할 리스트 초기화
    accuracy_list = []
    precision_list = []
    recall_list = []
    f1_score_list = []
    confusion_matrix_list = []

    best_f1_score = 0
    best_model = None

    for fold_idx, (train_idx, test_idx) in enumerate(cv.split(X_train, y_train), 1):
        X_train_fold, y_train_fold = X_train.iloc[train_idx], y_train.iloc[train_idx]
        X_test_fold, y_test_fold = X_train.iloc[test_idx], y_train.iloc[test_idx]

        # TabNet 모델 초기화
        model = TabNetClassifier(
            n_d=best_params['n_d'],
            n_a=best_params['n_a'],
            n_steps=best_params['n_steps'],
            gamma=best_params['gamma'],
            n_independent=best_params['n_independent'],
            n_shared=best_params['n_shared'],
            lambda_sparse=best_params['lambda_sparse'],
            verbose=0
        )

        # 모델 학습
        model.fit(
            X_train_fold.values, y_train_fold.values.ravel(),  # Convert y_train to 1D array using .ravel()
            eval_set=[(X_test_fold.values, y_test_fold.values.ravel())],  # Convert y_test to 1D array using .ravel()
            eval_metric=['accuracy'],
            patience=100,
            batch_size=1024,
            virtual_batch_size=128,
            max_epochs=1000
        )

        # 테스트 데이터에 대한 예측
        y_pred = model.predict(X_test_fold.values)

        # 평가 지표 계산
        accuracy = accuracy_score(y_test_fold, y_pred)
        precision = precision_score(y_test_fold, y_pred)
        recall = recall_score(y_test_fold, y_pred)
        f1 = f1_score(y_test_fold, y_pred)
        conf_matrix = confusion_matrix(y_test_fold, y_pred)

        # 각 fold 별 평가 지표를 리스트에 추가
        accuracy_list.append(accuracy)
        precision_list.append(precision)
        recall_list.append(recall)
        f1_score_list.append(f1)
        confusion_matrix_list.append(conf_matrix)

        print(f"Fold {fold_idx}")
        print(f"Accuracy: {accuracy}")
        print(f"Precision: {precision}")
        print(f"Recall: {recall}")
        print(f"F1 score: {f1}")
        print("Confusion Matrix:")
        print(conf_matrix)
        print("------------------------------")

        # 가장 좋은 f1-score 값을 가진 모델을 저장
        if f1 > best_f1_score:
            best_f1_score = f1
            best_model = model

    # 가장 좋은 f1-score 값을 가진 모델로 최종 예측 수행
    y_pred_final = best_model.predict(X_test.values)

    # 평가 지표 계산
    accuracy_final = accuracy_score(y_test, y_pred_final)
    precision_final = precision_score(y_test, y_pred_final)
    recall_final = recall_score(y_test, y_pred_final)
    f1_final = f1_score(y_test, y_pred_final)
    conf_matrix_final = confusion_matrix(y_test, y_pred_final)  # 테스트 데이터에 대한 Confusion Matrix 계산

    print("Final Test Results")
    print(f"Accuracy: {accuracy_final}")
    print(f"Precision: {precision_final}")
    print(f"Recall: {recall_final}")
    print(f"F1 score: {f1_final}")
    print("Confusion Matrix:")
    print(conf_matrix_final)

    return accuracy_list, precision_list, recall_list, f1_score_list

In [8]:
# 함수를 호출하여 cross validation과 test를 수행합니다.
evaluate_tabnet(X_train_sum, y_train, X_test_sum, y_test)


Early stopping occurred at epoch 100 with best_epoch = 0 and best_val_0_accuracy = 0.5
Fold 1
Accuracy: 0.5
Precision: 0.0
Recall: 0.0
F1 score: 0.0
Confusion Matrix:
[[9 0]
 [9 0]]
------------------------------

Early stopping occurred at epoch 100 with best_epoch = 0 and best_val_0_accuracy = 0.5
Fold 2
Accuracy: 0.5
Precision: 0.0
Recall: 0.0
F1 score: 0.0
Confusion Matrix:
[[9 0]
 [9 0]]
------------------------------

Early stopping occurred at epoch 100 with best_epoch = 0 and best_val_0_accuracy = 0.5
Fold 3
Accuracy: 0.5
Precision: 0.0
Recall: 0.0
F1 score: 0.0
Confusion Matrix:
[[9 0]
 [9 0]]
------------------------------

Early stopping occurred at epoch 100 with best_epoch = 0 and best_val_0_accuracy = 0.5
Fold 4
Accuracy: 0.5
Precision: 0.0
Recall: 0.0
F1 score: 0.0
Confusion Matrix:
[[9 0]
 [9 0]]
------------------------------

Early stopping occurred at epoch 100 with best_epoch = 0 and best_val_0_accuracy = 0.5
Fold 5
Accuracy: 0.5
Precision: 0.0
Recall: 0.0
F1 score

AttributeError: 'NoneType' object has no attribute 'predict'

---

In [10]:
import pandas as pd
import numpy as np
from pytorch_tabnet.tab_model import TabNetClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

def evaluate_tabnet(X_train, y_train, X_test, y_test):
    # Stratified 5-fold 교차검증 설정
    cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=0)

    # 최적 하이퍼파라미터 설정 (여기서는 고정값으로 사용)
    best_params = {
        'n_d': 8,  # Number of decision steps (also known as the number of features for attention)
        'n_a': 8,  # Number of attention features (output dimension of each attention head)
        'n_steps': 3,  # Number of steps in the architecture (usually between 3 and 10)
        'gamma': 1.5,  # The factor by which to scale the contribution of each augmented sample
        'n_independent': 2,  # Number of independent GLU layers in each decision step
        'n_shared': 2,  # Number of shared GLU layers in each decision step
        'lambda_sparse': 0.001  # The sparsity loss weight
    }

    # 각 fold 별 평가 지표를 저장할 리스트 초기화
    accuracy_list = []
    precision_list = []
    recall_list = []
    f1_score_list = []
    confusion_matrix_list = []

    best_f1_score = 0
    best_model = None

    for fold_idx, (train_idx, test_idx) in enumerate(cv.split(X_train, y_train), 1):
        X_train_fold, y_train_fold = X_train.iloc[train_idx], y_train.iloc[train_idx]
        X_test_fold, y_test_fold = X_train.iloc[test_idx], y_train.iloc[test_idx]

        # TabNet 모델 초기화
        model = TabNetClassifier(
            n_d=best_params['n_d'],
            n_a=best_params['n_a'],
            n_steps=best_params['n_steps'],
            gamma=best_params['gamma'],
            n_independent=best_params['n_independent'],
            n_shared=best_params['n_shared'],
            lambda_sparse=best_params['lambda_sparse'],
            verbose=0
        )

        # 모델 학습
        model.fit(
            X_train_fold.values, y_train_fold.values.ravel(),  # Convert y_train to 1D array using .ravel()
            eval_set=[(X_test_fold.values, y_test_fold.values.ravel())],  # Convert y_test to 1D array using .ravel()
            eval_metric=['accuracy'],
            patience=100,
            batch_size=1024,
            virtual_batch_size=128,
            max_epochs=1000
        )

        # 테스트 데이터에 대한 예측
        y_pred = model.predict(X_test_fold.values)

        # 평가 지표 계산
        accuracy = accuracy_score(y_test_fold, y_pred)
        precision = precision_score(y_test_fold, y_pred)
        recall = recall_score(y_test_fold, y_pred)
        f1 = f1_score(y_test_fold, y_pred)
        conf_matrix = confusion_matrix(y_test_fold, y_pred)

        # 각 fold 별 평가 지표를 리스트에 추가
        accuracy_list.append(accuracy)
        precision_list.append(precision)
        recall_list.append(recall)
        f1_score_list.append(f1)
        confusion_matrix_list.append(conf_matrix)

        print(f"Fold {fold_idx}")
        print(f"Accuracy: {accuracy}")
        print(f"Precision: {precision}")
        print(f"Recall: {recall}")
        print(f"F1 score: {f1}")
        print("Confusion Matrix:")
        print(conf_matrix)
        print("------------------------------")

        # 가장 좋은 f1-score 값을 가진 모델을 저장
        if f1 > best_f1_score:
            best_f1_score = f1
            best_model = model

    # 가장 좋은 f1-score 값을 가진 모델이 없는 경우 예외 처리
    if best_model is None:
        raise ValueError("No best model found. Check your hyperparameters or increase the number of epochs.")

    # 가장 좋은 f1-score 값을 가진 모델로 최종 예측 수행
    y_pred_final = best_model.predict(X_test.values)

    # 평가 지표 계산
    accuracy_final = accuracy_score(y_test, y_pred_final)
    precision_final = precision_score(y_test, y_pred_final)
    recall_final = recall_score(y_test, y_pred_final)
    f1_final = f1_score(y_test, y_pred_final)
    conf_matrix_final = confusion_matrix(y_test, y_pred_final)  # 테스트 데이터에 대한 Confusion Matrix 계산

    print("Final Test Results")
    print(f"Accuracy: {accuracy_final}")
    print(f"Precision: {precision_final}")
    print(f"Recall: {recall_final}")
    print(f"F1 score: {f1_final}")
    print("Confusion Matrix:")
    print(conf_matrix_final)

    return accuracy_list, precision_list, recall_list, f1_score_list

# 함수를 호출하여 cross validation과 test를 수행합니다.
evaluate_tabnet(X_train_sc, y_train, X_test_sc, y_test)



Early stopping occurred at epoch 100 with best_epoch = 0 and best_val_0_accuracy = 0.5
Fold 1
Accuracy: 0.5
Precision: 0.0
Recall: 0.0
F1 score: 0.0
Confusion Matrix:
[[9 0]
 [9 0]]
------------------------------

Early stopping occurred at epoch 100 with best_epoch = 0 and best_val_0_accuracy = 0.5
Fold 2
Accuracy: 0.5
Precision: 0.0
Recall: 0.0
F1 score: 0.0
Confusion Matrix:
[[9 0]
 [9 0]]
------------------------------

Early stopping occurred at epoch 100 with best_epoch = 0 and best_val_0_accuracy = 0.5
Fold 3
Accuracy: 0.5
Precision: 0.0
Recall: 0.0
F1 score: 0.0
Confusion Matrix:
[[9 0]
 [9 0]]
------------------------------

Early stopping occurred at epoch 100 with best_epoch = 0 and best_val_0_accuracy = 0.5
Fold 4
Accuracy: 0.5
Precision: 0.0
Recall: 0.0
F1 score: 0.0
Confusion Matrix:
[[9 0]
 [9 0]]
------------------------------

Early stopping occurred at epoch 100 with best_epoch = 0 and best_val_0_accuracy = 0.5
Fold 5
Accuracy: 0.5
Precision: 0.0
Recall: 0.0
F1 score

ValueError: No best model found. Check your hyperparameters or increase the number of epochs.